-- Creazione tabella autori
CREATE TABLE autori (
    id_autore INTEGER PRIMARY KEY,
    nome VARCHAR(40),
    cognome VARCHAR(40),
    data_nascita DATE
);

-- Creazione tabella libri
CREATE TABLE libri (
    id_libro INTEGER PRIMARY KEY,
    titolo VARCHAR(100),
    categoria VARCHAR(40),
    data_pubblicazione DATE
);

-- Creazione tabella libri_autori (tabella di relazione molti-a-molti)
CREATE TABLE libri_autori (
    id_autore INTEGER NOT NULL,
    id_libro INTEGER NOT NULL,
    PRIMARY KEY (id_autore, id_libro),
    FOREIGN KEY (id_autore) REFERENCES autori(id_autore),
    FOREIGN KEY (id_libro) REFERENCES libri(id_libro)
);


-- Creazione tabella utenti
CREATE TABLE utenti (
    id_utente INTEGER PRIMARY KEY,
    nome VARCHAR(40),
    cognome VARCHAR(40),
    data_nascita DATE,
    numero_telefono INTEGER
);

-- Creazione tabella prestiti
CREATE TABLE prestiti (
    id_utente INTEGER NOT NULL,
    id_libro INTEGER NOT NULL,
    timestamp_prestito_inizio TIMESTAMP NOT NULL,
    timestamp_prestito_fine TIMESTAMP,
    PRIMARY KEY (id_utente, id_libro, timestamp_prestito_inizio),
    FOREIGN KEY (id_utente) REFERENCES utenti(id_utente),
    FOREIGN KEY (id_libro) REFERENCES libri(id_libro)
);

-- Creazione delle sequenze (IDENTITY) per le colonne con AUTO_INCREMENT in PostgreSQL
CREATE SEQUENCE autori_id_autore_seq AS INTEGER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE libri_id_libro_seq AS INTEGER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE utenti_id_utente_seq AS INTEGER START WITH 1 INCREMENT BY 1;

-- Aggiunta del valore iniziale alle sequenze
-- (Potresti dover modificare il valore iniziale in base al dump di PostgreSQL)
--INSERT INTO autori_id_autore_seq (next_val) VALUES (2);
--INSERT INTO libri_id_libro_seq (next_val) VALUES (2);
--INSERT INTO utenti_id_utente_seq (next_val) VALUES (2);

-- Impostazione delle sequenze per le colonne con AUTO_INCREMENT
--ALTER TABLE autori ALTER COLUMN id_autore SET GENERATED BY DEFAULT AS IDENTITY;
--ALTER TABLE libri ALTER COLUMN id_libro SET GENERATED BY DEFAULT AS IDENTITY;
--ALTER TABLE utenti ALTER COLUMN id_utente SET GENERATED BY DEFAULT AS IDENTITY;

-- Inserimento dei dati nelle tabelle (potresti dover adattare i dati in base al dump di PostgreSQL)
--INSERT INTO autori (id_autore, nome, cognome, data_nascita) VALUES (1, 'NomeAutore', 'CognomeAutore', '1990-01-01');
--INSERT INTO libri (id_libro, titolo, categoria, data_pubblicazione) VALUES (1, 'TitoloLibro', 'CategoriaLibro', '2000-01-01');
--INSERT INTO libri_autori (id_autore, id_libro) VALUES (1, 1);
--INSERT INTO utenti (id_utente, nome, cognome, data_nascita, numero_telefono) VALUES (1, 'NomeUtente', 'CognomeUtente', '1995-01-10', 333444555);
-- Query di inserimento per la tabella "autori"
INSERT INTO autori (id_autore, nome, cognome, data_nascita) VALUES (1, 'NomeAutore1', 'CognomeAutore1', '1990-01-01');
INSERT INTO autori (id_autore, nome, cognome, data_nascita) VALUES (2, 'NomeAutore2', 'CognomeAutore2', '1985-03-15');
INSERT INTO autori (id_autore, nome, cognome, data_nascita) VALUES (3, 'NomeAutore3', 'CognomeAutore3', '1978-09-30');
-- Aggiungi altre 7 query di inserimento per gli altri autori...

-- Query di inserimento per la tabella "libri"
INSERT INTO libri (id_libro, titolo, categoria, data_pubblicazione) VALUES (1, 'TitoloLibro1', 'CategoriaLibro1', '2000-01-01');
INSERT INTO libri (id_libro, titolo, categoria, data_pubblicazione) VALUES (2, 'TitoloLibro2', 'CategoriaLibro2', '1998-06-20');
INSERT INTO libri (id_libro, titolo, categoria, data_pubblicazione) VALUES (3, 'TitoloLibro3', 'CategoriaLibro3', '2005-12-12');
-- Aggiungi altre 7 query di inserimento per gli altri libri...

-- Query di inserimento per la tabella "libri_autori"
INSERT INTO libri_autori (id_autore, id_libro) VALUES (1, 1);
INSERT INTO libri_autori (id_autore, id_libro) VALUES (2, 2);
INSERT INTO libri_autori (id_autore, id_libro) VALUES (3, 3);
-- Aggiungi altre 7 query di inserimento per altre associazioni tra autori e libri...

-- Query di inserimento per la tabella "utenti"
INSERT INTO utenti (id_utente, nome, cognome, data_nascita, numero_telefono) VALUES (1, 'NomeUtente1', 'CognomeUtente1', '1995-01-10', 333444555);
INSERT INTO utenti (id_utente, nome, cognome, data_nascita, numero_telefono) VALUES (2, 'NomeUtente2', 'CognomeUtente2', '1992-11-25', 111222333);
INSERT INTO utenti (id_utente, nome, cognome, data_nascita, numero_telefono) VALUES (3, 'NomeUtente3', 'CognomeUtente3', '1988-07-05', 444555666);
-- Aggiungi altre 7 query di inserimento per gli altri utenti...

-- NOTA: La tabella "prestiti" è stata già definita con la CREATE TABLE.
-- Pertanto, di seguito aggiungiamo solo le query di inserimento per i prestiti.

-- Query di inserimento per la tabella "prestiti"
INSERT INTO prestiti (id_utente, id_libro, timestamp_prestito_inizio) VALUES (1, 1, '2023-07-24 12:00:00');
INSERT INTO prestiti (id_utente, id_libro, timestamp_prestito_inizio) VALUES (2, 2, '2023-07-25 10:30:00');
INSERT INTO prestiti (id_utente, id_libro, timestamp_prestito_inizio) VALUES (3, 3, '2023-07-26 14:45:00');
-- Aggiungi altre 7 query di inserimento per gli altri prestiti...
